language: node_js
script: echo 'abc'

deploy:
  - provider: s3
    access_key_id: $access_key_id
    secret_access_key: $access_key
    bucket: storageforgithubdeploy
    region: ap-northeast-2
    skip_cleanup: true
  
