language: node_js
script: echo 'abc'

deploy:
  - provider: s3
    access_key_id: $access_key_id
    secret_access_key: $access_key
    bucket: storageforgithubdeploy
    region: ap-northeast-2
    skip_cleanup: true
  - provider: codedeploy	  
    access_key_id: $access_key_deployer_id
    s3_key: 
    secret_access_key: $access_key_deployer
    bucket: storageforgithubdeploy	
    application: CodeDeployGitHubDemo-App	
    deployment_group: CodeDeployGitHubDemo-DepGrp	
    region: ap-northeast-2	
    wait-until-deployed: true
  
